"""Table: the eight models, how each was called, and what each delivered.

A reader should find the models at a glance, as in the TRB companion paper's model table, and see
their results on the same row. Agreement cells are shaded in the reference color by value, and
exit-claim cells in the model-claim color by value, so a dark cell is good in the first block and
bad in the second. Every number is read from the analysis outputs; nothing is typed.

Cells are built with textcolor and newline inside fixed-width m-columns. An earlier version used
color switches inside makecell, which shifted white text out of its shaded cell.

Writes paper/tables/q1_tab_models.tex
Run: py evactime/Q1_tab_models.py
"""
import json, pathlib, sys
import pandas as pd

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "evactime" / "outputs"
TAB = ROOT / "paper" / "tables"
sys.path.insert(0, str(ROOT / "evactime"))
import tabviz as tv
from vlm_records import load_records

MODELS = [  # (key, name, developer, route) in the order the Method lists them
    ("gemini-3.1-pro-preview", "Gemini 3.1 Pro", "Google", "native"),
    ("gemini-3-flash-preview", "Gemini 3 Flash", "Google", "native"),
    ("gemini-3.1-flash-lite", "Gemini 3.1 Flash-Lite", "Google", "native"),
    ("openai/gpt-5.2", "GPT-5.2", "OpenAI", "OpenRouter"),
    ("anthropic/claude-opus-4.8", "Claude Opus 4.8", "Anthropic", "OpenRouter"),
    ("anthropic/claude-sonnet-5", "Claude Sonnet 5", "Anthropic", "OpenRouter"),
    ("qwen/qwen3-vl-235b-a22b-instruct", "Qwen3-VL 235B", "Alibaba", "OpenRouter"),
    ("meta-llama/llama-4-maverick", "Llama 4 Maverick", "Meta", "OpenRouter"),
]
FMT = {"A,A0,B": "V, M, F", "B": "F"}


def cell(value, sub, color, scale=100, cap=60):
    """Two-line cell shaded by value: the value on top, its support underneath."""
    shade = int(round(min(value / scale, 1.0) * cap))
    ink = "white" if shade > 38 else "black"
    return (rf"\cellcolor{{{color}!{shade}}}\makecell{{\textcolor{{{ink}}}{{{value:.1f}}}\\[-1pt]"
            rf"\scriptsize\textcolor{{{ink}}}{{{sub}}}}}")


def main():
    c2 = pd.read_csv(OUT / "C2_confusion.csv")
    c4 = pd.read_csv(OUT / "C4_script_completion.csv")
    _, _, per = load_records()
    abl = json.load(open(OUT / "C6_neutral_prompt.json", encoding="utf-8"))
    nat = abl["native"]["cells"]
    neutral = {k.split("|")[0]: v for k, v in abl["cells"].items() if k.endswith("|B")}
    rows = []
    for key, name, dev, route in MODELS:
        g2, g4 = c2[c2.model == key], c4[c4.model == key]
        fm = FMT[",".join(sorted(g4.cond.unique()))]
        use = per[key]["kept"], per[key]["on_disk"]
        obj = cell(100 * g2.correct.mean(), f"$n={len(g2)}$", "tvSlate")
        reg = cell(100 * g2.region_hit.mean(), f"$n={len(g2)}$", "tvSlate")
        ex = cell(100 * g4.transit.mean(), f"$n={len(g4)}$", "tvEmber")
        if key == "gemini-3-flash-preview":
            neu = (rf"\makecell{{{100 * nat['A']['v3']:.1f} / {100 * nat['B']['v3']:.1f}\\[-1pt]"
                   rf"\scriptsize from {100 * nat['A']['v2']:.1f} / {100 * nat['B']['v2']:.1f}}}")
        elif key in neutral:
            c = neutral[key]
            neu = cell(100 * c["v3"], f"from {100 * c['v2']:.1f}", "tvEmber")
        else:
            neu = r"\textcolor{tvSub}{not run}"
        rows.append(rf"{name} & {dev} & {route} & {fm} & {use[0]}/{use[1]} & {obj} & {reg} & "
                    rf"{ex} & {neu} \\")
    head = (r" & & & & & \multicolumn{2}{c}{\textbf{Agreement (\%)}} & "
            r"\multicolumn{2}{c}{\textbf{Exit claims (\%)}} \\" "\n"
            r"\cmidrule(lr){6-7}\cmidrule(lr){8-9}" "\n"
            r"\textbf{Model} & \textbf{Developer} & \textbf{Route} & \textbf{Input} & "
            r"\textbf{Usable} & \textbf{Object} & \textbf{Region} & \textbf{Original} & "
            r"\textbf{Neutral} \\")
    col = r">{\centering\arraybackslash}m{1.2cm}"
    tex = "\n".join([
        "% generated by evactime/Q1_tab_models.py; do not edit",
        tv.preamble(),
        r"\begin{table}[!ht]", r"\centering\footnotesize", r"\begin{threeparttable}",
        r"\caption{Models, Access and Results}\label{tab:models}",
        r"\setlength{\tabcolsep}{5pt}\renewcommand{\arraystretch}{1.3}",
        r"\begin{tabular}{@{}l l l c c *{4}{c}@{}}",
        r"\toprule", head, r"\midrule", "\n".join(rows), r"\bottomrule", r"\end{tabular}",
        r"\begin{tablenotes}[flushleft]\scriptsize",
        r"\item[] \textit{Note:} Input formats are V video with audio, M muted video and F frames at one per second. "
        r"Usable counts calls with a complete response. The neutral column gives same-day paired "
        r"rates on frames, and for Gemini 3 Flash on video and frames through its native interface.",
        r"\end{tablenotes}", r"\end{threeparttable}", r"\end{table}"])
    (TAB / "q1_tab_models.tex").write_text(tex + "\n", encoding="utf-8")
    print("wrote", TAB / "q1_tab_models.tex")


if __name__ == "__main__":
    main()
