"""Literature positioning table (Table 1 of the Literature Review), built from the scored grid.

Each cell is a Harvey ball read from docs/litreview/grid_scores.csv, which carries the score, a
quotation and its location for every cell. The quotations are checked against the full texts by
docs/litreview/verify_grid_quotes.py, and this script refuses to build if that check fails, so the
table can never show a cell whose evidence has not been found in its source.

Rows are grouped by strand of literature and this study comes last. There is no tally column,
because a count of filled balls reads as a scoreboard rather than a map of the literature.

Writes paper/tables/q1_tab_positioning.tex and paper/supplement/positioning_evidence.csv.
Run: py evactime/Q1_tab_positioning.py
"""
import csv, pathlib, subprocess, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
LIT = ROOT / "docs" / "litreview"
TAB = ROOT / "paper" / "tables"
SUP = ROOT / "paper" / "supplement"
SUP.mkdir(parents=True, exist_ok=True)
sys.path.insert(0, str(ROOT / "evactime"))
from palette import SLATE, SHELL, INK

COLS = [("Evac", "Evacuation setting"), ("Truth", "Instrumented reference"),
        ("Object", "Object-level attention"), ("Narr", "Narrative faithfulness"),
        ("Chance", "Chance control"), ("Input", "Input format as a factor"),
        ("Breadth", "Model breadth"), ("Audit", "Agreement reported")]

STRANDS = [
    ("Vision-language models in transport safety", [
        ("zhang2025seeunsafe", "Crash video analysis"),
        ("skender2025accidentdetect", "Simulated crash imagery"),
        ("munir2025pedvlm", "Pedestrian intention, street video"),
        ("li2026egocentricintent", "Pedestrian intention in VR"),
    ]),
    ("Disaster and evacuation imagery", [
        ("ding2024hbdset", "Evacuee behavior detection"),
        ("zhang2026disasterbench", "Disaster response, aerial images"),
    ]),
    ("Video-language benchmarks", [
        ("fu2024videomme", "General video, multiple choice"),
        ("cai2024temporalbench", "Fine-grained temporal events"),
        ("shangguan2024tomato", "Temporal reasoning"),
    ]),
    ("Hallucination benchmarks", [
        ("li2023pope", "Object hallucination, images"),
        ("wang2024videohallucer", "Video hallucination"),
        ("zhang2024eventhallusion", "Event hallucination, video"),
    ]),
]
THIS = ("this_study", "VR evacuation, engine record")
BALL = {"full": r"\hbfull", "partial": r"\hbhalf", "absent": r"\hbnone"}


def main():
    chk = subprocess.run([sys.executable, str(LIT / "verify_grid_quotes.py")],
                         capture_output=True, text=True, encoding="utf-8")
    if chk.returncode != 0:
        print(chk.stdout)
        sys.exit("quote verification failed; the table is not built")
    rows = list(csv.DictReader(open(LIT / "grid_scores.csv", encoding="utf-8")))
    grid = {(r["key"], r["col"]): r for r in rows}
    used = [k for _, ks in STRANDS for k, _ in ks] + [THIS[0]]
    missing = [(k, c) for k in used for c, _ in COLS if (k, c) not in grid]
    if missing:
        sys.exit(f"cells without a score: {missing}")

    import tabviz as tv
    ncol = 2 + len(COLS)
    grp = (r" & & \multicolumn{2}{c}{\textbf{Data}} & "
           r"\multicolumn{2}{c}{\textbf{Claims}} & "
           r"\multicolumn{4}{c}{\textbf{Design}} \\" "\n"
           r"\cmidrule(lr){3-4}\cmidrule(lr){5-6}\cmidrule(l){7-10}")
    head = grp + "\n" + (r"\textbf{Study} & \textbf{Setting} & " + " & ".join(
        r"\rotatebox{90}{\textbf{" + h + "}}" for _, h in COLS) + r" \\")
    body = []
    prior = []
    for strand, keys in STRANDS:
        body.append(tv.group(strand, ncol))
        for k, setting in keys:
            prior.append(k)
            cells = " & ".join(BALL[grid[(k, c)]["score"]] for c, _ in COLS)
            body.append(rf"\citet{{{k}}} & {setting} & {cells} \\")
    # Column-wise coverage of the prior studies, as a vertical micro-bar per criterion (full in
    # ink, partial in gray, absent as open frame). It maps where the literature is thin without
    # scoring any single study.
    cov = []
    for c, _ in COLS:
        sc = [grid[(k, c)]["score"] for k in prior]
        cov.append(tv.coverage(sc.count("full"), sc.count("partial"), sc.count("absent")))
    body.append(r"\addlinespace[2pt]" + "\n" +
                rf"\multicolumn{{2}}{{@{{}}l}}{{\textit{{Coverage in the {len(prior)} prior studies}}}}"
                " & " + " & ".join(cov) + r" \\")
    cells = []
    for c, _ in COLS:
        b = BALL[grid[(THIS[0], c)]["score"]].replace(r"\hb", r"\hbthis")
        cells.append(b + (r"\rlap{\textsuperscript{a}}" if c == "Input" else ""))
    body.append(r"\midrule" + "\n" +
                rf"\textbf{{This study}} & {THIS[1]} & " + " & ".join(cells) + r" \\")

    tex = "\n".join([
        "% generated by evactime/Q1_tab_positioning.py from docs/litreview/grid_scores.csv; do not edit",
        tv.preamble(),
        rf"\definecolor{{hbcol}}{{HTML}}{{{INK.lstrip('#')}}}",
        rf"\definecolor{{hbacc}}{{HTML}}{{{SLATE.lstrip('#')}}}",
        r"\providecommand{\hbfull}{\tikz[baseline=-0.6ex]\fill[hbcol] (0,0) circle (0.7ex);}",
        r"\providecommand{\hbhalf}{\tikz[baseline=-0.6ex]{\draw[hbcol,line width=0.4pt] (0,0) circle (0.7ex);"
        r"\fill[hbcol] (0,0) -- (90:0.7ex) arc (90:270:0.7ex) -- cycle;}}",
        r"\providecommand{\hbnone}{\tikz[baseline=-0.6ex]\draw[hbcol,line width=0.4pt] (0,0) circle (0.7ex);}",
        r"\providecommand{\hbthisfull}{\tikz[baseline=-0.6ex]\fill[hbacc] (0,0) circle (0.7ex);}",
        r"\providecommand{\hbthishalf}{\tikz[baseline=-0.6ex]{\draw[hbacc,line width=0.4pt] (0,0) circle (0.7ex);"
        r"\fill[hbacc] (0,0) -- (90:0.7ex) arc (90:270:0.7ex) -- cycle;}}",
        r"\providecommand{\hbthisnone}{\tikz[baseline=-0.6ex]\draw[hbacc,line width=0.4pt] (0,0) circle (0.7ex);}",
        r"\begin{table}[!ht]",
        r"\centering\footnotesize",
        r"\begin{threeparttable}",
        r"\caption{Positioning Against Prior Evaluations}\label{tab:positioning}",
        r"\setlength{\tabcolsep}{4.5pt}",
        r"\begin{tabular}{l >{\raggedright\arraybackslash}p{4.6cm} " + " ".join(["c"] * len(COLS)) + "}",
        r"\toprule", head, r"\midrule", "\n".join(body), r"\bottomrule", r"\end{tabular}",
        r"\begin{tablenotes}[flushleft]\scriptsize",
        r"\item[] \textit{Note:} \hbfull\ full, \hbhalf\ partial, \hbnone\ absent. Criteria and a supporting "
        r"quotation for every cell are in the Supplementary Material. Coverage bars count the prior "
        r"studies meeting each criterion in full (black) or in part (gray).",
        r"\item[a] Audio conditions on the three video-capable models.",
        r"\end{tablenotes}",
        r"\end{threeparttable}",
        r"\end{table}",
    ])
    (TAB / "q1_tab_positioning.tex").write_text(tex + "\n", encoding="utf-8")

    # per-cell evidence for the supplement
    from verify_grid_quotes import SOURCE  # noqa: E402  (path added below)
    with open(SUP / "positioning_evidence.csv", "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["study", "criterion", "score", "evidence", "location", "version_read", "note"])
        for k in used:
            for c, h in COLS:
                r = grid[(k, c)]
                note = r["note"] + (f" Harmonized: {r['harmonized']}." if r["harmonized"] else "")
                w.writerow([k, h, r["score"], r["quote"], r["location"],
                            SOURCE.get(k, ("", "this manuscript"))[1], note.strip()])
    print("wrote", TAB / "q1_tab_positioning.tex")
    print("wrote", SUP / "positioning_evidence.csv")


if __name__ == "__main__":
    sys.path.insert(0, str(LIT))
    main()
